"""Add created_at field

Revision ID: 98179609f640
Revises: fde97a723df2
Create Date: 2024-05-20 14:16:23.518445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98179609f640'
down_revision = 'fde97a723df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
